# Generated by Django 4.1.2 on 2022-10-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='users.user')),
                ('enthusiast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enthusiast', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=1300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='gallery_profile_pics')),
                ('banner_picture', models.ImageField(blank=True, null=True, upload_to='gallery_banner_pics')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_works')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=230, null=True)),
                ('category', models.ManyToManyField(to='gallery.category')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
            ],
        ),
    ]
