// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3AHe_eLUVCkZeu1hZs4IizzN2jwCza7c',
    appId: '1:300668063431:web:64f225923c1d8cef0c38e2',
    messagingSenderId: '300668063431',
    projectId: 'artzy-app-production',
    authDomain: 'artzy-app-production.firebaseapp.com',
    storageBucket: 'artzy-app-production.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjBgEV1xelqAJ1_kiT4U7QMjOy0kLVlo',
    appId: '1:300668063431:android:f25705f7ad206e080c38e2',
    messagingSenderId: '300668063431',
    projectId: 'artzy-app-production',
    storageBucket: 'artzy-app-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzE2t6MG3xbQ-yYKxY6T056twD-NzWgyY',
    appId: '1:300668063431:ios:bbb066af86f0cf570c38e2',
    messagingSenderId: '300668063431',
    projectId: 'artzy-app-production',
    storageBucket: 'artzy-app-production.appspot.com',
    iosClientId: '300668063431-t5tcb2h7tjg3o5tjmebdpd93q2ajnl37.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
